/**
 * script-types.ts
 *
 * The shape of a campaign script. Separated from the registry so a
 * script file can import the type without importing the registry that
 * imports it back.
 */

import type { CampaignType } from "../domain/campaign-types";

export interface CampaignScript {
  readonly id: string;
  readonly version: string;
  readonly campaignType: CampaignType;
  readonly label: string;

  /**
   * Appended AFTER the existing master system prompt, never in place
   * of it. Every conversational rule the voice agent already follows
   * stays in force; this only adds the scenario.
   */
  readonly systemPromptAppendix: string;

  /** Spoken verbatim as the first line. Not generated by the model. */
  readonly openingLineTemplate: string;

  /** When true, a contact with no name is a validation error at import. */
  readonly requiresName: boolean;

  /** True until the approved wording is installed. Blocks READY. */
  readonly isPlaceholder: boolean;
}

/** A script bound to one campaign, with its content hash pinned. */
export interface ScriptBinding {
  readonly scriptId: string;
  readonly scriptVersion: string;
  readonly scriptHash: string;
}
